services:
  nest-vue-web:
    image: x/nest-vue-web:latest
    container_name: nest-vue-web
    ports:
      - '80:80'
    restart: always
    networks:
      - nest_vue_net
  mysql:
    image: mysql:latest
    container_name: nest-vue-mysql
    restart: always
    env_file:
      - .env
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '${DB_PORT}:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci # 设置utf8字符集
    volumes:
      - /opt/www/mysql/data:/var/lib/mysql
      # 初始化mysql数据脚本，如果./mysql/data数据目录已存在，则不会执行初始化脚本
      - ./deploy/sql/:/docker-entrypoint-initdb.d/
    networks:
      - nest_vue_net

  nest-vue-server:
    # build: 从当前路径构建镜像
    build:
      context: .
      args:
        - PROJECT_DIR=${PROJECT_DIR}
    image: x/nest-vue-server:latest
    container_name: nest-vue-server
    restart: always
    env_file:
      - .env
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${APP_PORT}:${APP_PORT}'
    # 当前服务启动之前先要把depends_on指定的服务启动起来才行
    depends_on:
      - mysql
    networks:
      - nest_vue_net

networks:
  nest_vue_net:
    name: nest_vue_net
